name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update APT
      run: sudo apt-get update
    - name: Install Dependencies
      run: |
        sudo apt-get install -y build-essential git make autoconf automake libtool \
        pkg-config patchelf ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
        libaudio-dev libjack-dev libsndio-dev libsamplerate0-dev libx11-dev libxext-dev \
        libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libwayland-dev \
        libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
        libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev
    - name: Pull Dependencies
      run: make getdeps -j
    - name: Build
      run: make
    - name: Artifact AppImage
      uses: actions/upload-artifact@v3
      with:
        name: AppImage
        path: love-12.0-development.AppImage
    - name: Artifact Tape Archive
      uses: actions/upload-artifact@v3
      with:
        name: tar.gz
        path: love-12.0-development.tar.gz
